# fly.toml app configuration file generated for yummers on 2026-06-03T13:21:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yummers'
primary_region = 'ams'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
